const $=id=>document.getElementById(id),cv=$('game'),g=cv.getContext('2d'),W=360,H=540;
const colors=[['#ffa8d1','#e6378a'],['#9edbff','#3285e8'],['#b4f39a','#40ba5b'],['#ffe58b','#edae2b'],['#d7aaff','#9254db'],['#ffc38b','#ec792d']];
// Personajes extraídos de la referencia visual aprobada; el dibujo anterior queda como respaldo.
const plushSprites=['pink','blue','green','yellow','purple','orange'].map(name=>{const im=new Image();im.src=new URL('./assets/plush-'+name+'.png',document.baseURI).href;return im});
let stars=Array.from({length:75},()=>({x:Math.random()*W,y:Math.random()*H,r:Math.random()*1.5+.3,v:10+Math.random()*20}));
let ship=180,enemies=[],shots=[],bits=[],waves=[],score=0,lives=3,level=1,time=0,spawn=0,inv=0,active=false,paused=false,holding=false,weapon=0,cool=[0,0,0],last=0,raf=0,moveDirection=0,dragPointer=null;
let ac=null,musicBus=null,fxBus=null,musicOn=true,sfxOn=true,musicTimer=null,step=0,next=0;
const cd=[.65,1.8,8],beat=60/126,melody=[659.25,587.33,523.25,440,523.25,587.33,659.25,783.99,698.46,659.25,587.33,523.25,493.88,523.25,587.33,440],bass=[110,110,130.81,130.81,146.83,146.83,98,98];
function audioInit(){try{if(!ac){ac=new (window.AudioContext||window.webkitAudioContext)();musicBus=ac.createGain();fxBus=ac.createGain();musicBus.gain.value=.12;fxBus.gain.value=.18;musicBus.connect(ac.destination);fxBus.connect(ac.destination)}ac.resume()}catch(e){musicOn=false;sfxOn=false;buttons()}}
function tone(f,t,d,type,v,bus,end){if(!ac||!bus)return;let o=ac.createOscillator(),a=ac.createGain();o.type=type;o.frequency.setValueAtTime(f,t);if(end)o.frequency.exponentialRampToValueAtTime(end,t+d);a.gain.setValueAtTime(.0001,t);a.gain.exponentialRampToValueAtTime(Math.max(.001,v),t+.009);a.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(a);a.connect(bus);o.start(t);o.stop(t+d+.02)}
function noise(t,d,v,bus){if(!ac)return;let b=ac.createBuffer(1,Math.ceil(ac.sampleRate*d),ac.sampleRate),arr=b.getChannelData(0);for(let i=0;i<arr.length;i++)arr[i]=Math.random()*2-1;let s=ac.createBufferSource(),f=ac.createBiquadFilter(),a=ac.createGain();s.buffer=b;f.type='highpass';f.frequency.value=1800;a.gain.setValueAtTime(v,t);a.gain.exponentialRampToValueAtTime(.001,t+d);s.connect(f);f.connect(a);a.connect(bus);s.start(t);s.stop(t+d)}
function musicTick(){if(!ac||!active||paused||!musicOn)return;while(next<ac.currentTime+.12){let s=step%16,t=next;if(s%4===0){tone(145,t,.22,'sine',.9,musicBus,43);tone(bass[Math.floor(step/4)%8]/2,t,.34,'sawtooth',.11,musicBus)}if(s%4===2)noise(t,.12,.19,musicBus);noise(t,.035,s%2===0?.045:.025,musicBus);if([3,6,11,14].includes(s))tone(225,t,.09,'triangle',.14,musicBus,115);if(s%2===1||s===0)tone(melody[step%16],t,.22,'triangle',.13,musicBus);if(s===0||s===8)[220,261.63,329.63].forEach((f,i)=>tone(f,t+i*.018,.6,'sine',.06,musicBus));step++;next+=beat/4}}
function musicStart(){if(!musicOn||!ac)return;musicBus.gain.setTargetAtTime(.12,ac.currentTime,.025);next=ac.currentTime+.06;clearInterval(musicTimer);musicTimer=setInterval(musicTick,25);musicTick()}
function musicStop(){clearInterval(musicTimer);musicTimer=null;if(ac)musicBus.gain.setTargetAtTime(0,ac.currentTime,.02)}
function fx(kind){if(!sfxOn||!ac)return;let t=ac.currentTime+.01;if(kind==='bullet')tone(450,t,.11,'square',.13,fxBus,160);if(kind==='laser')tone(1450,t,.28,'sawtooth',.18,fxBus,350);if(kind==='grenade')tone(280,t,.22,'triangle',.2,fxBus,90);if(kind==='boom'){noise(t,.24,.32,fxBus);tone(160,t,.29,'sawtooth',.25,fxBus,42)}if(kind==='big'){noise(t,.65,.65,fxBus);tone(130,t,.6,'sawtooth',.45,fxBus,35)}if(kind==='coin'){tone(740,t,.12,'sine',.3,fxBus);tone(1100,t+.09,.19,'sine',.26,fxBus)}if(kind==='hurt')tone(230,t,.4,'sawtooth',.28,fxBus,60)}
function circle(x,y,r,c){g.fillStyle=c;g.beginPath();g.arc(x,y,r,0,Math.PI*2);g.fill()}
function plush(e){const sprite=plushSprites[e.spriteIndex];if(sprite&&sprite.complete&&sprite.naturalWidth){g.save();g.translate(e.x,e.y);g.rotate(Math.sin(time*3+e.phase)*.07);g.drawImage(sprite,-35,-40,70,80);g.restore();return}g.save();g.translate(e.x,e.y);g.rotate(Math.sin(time*3+e.phase)*.07);let c=e.color;g.lineCap='round';g.lineWidth=11;g.strokeStyle=c[1];for(let p of [[-15,-20,-22,-34],[15,-20,22,-34],[-23,0,-34,5],[23,0,34,5],[-10,23,-13,35],[0,25,0,37],[10,23,13,35]]){g.beginPath();g.moveTo(p[0],p[1]);g.lineTo(p[2],p[3]);g.stroke()}g.strokeStyle=c[0];g.lineWidth=7;for(let p of [[-15,-20,-22,-34],[15,-20,22,-34],[-23,0,-34,5],[23,0,34,5]]){g.beginPath();g.moveTo(p[0],p[1]);g.lineTo(p[2],p[3]);g.stroke()}g.shadowColor=c[1];g.shadowBlur=10;let gr=g.createRadialGradient(-10,-17,2,0,0,35);gr.addColorStop(0,'#ffffff');gr.addColorStop(.27,c[0]);gr.addColorStop(1,c[1]);g.fillStyle=gr;g.beginPath();g.ellipse(0,0,27,31,0,0,Math.PI*2);g.fill();g.shadowBlur=0;g.fillStyle='#fff9';g.beginPath();g.ellipse(0,12,20,13,0,0,Math.PI*2);g.fill();g.strokeStyle='#ffffff99';g.lineWidth=1.3;for(let y of [6,13,20]){g.beginPath();g.moveTo(-18,y);g.lineTo(18,y);g.stroke()}circle(-10,-8,3,'#162039');circle(10,-8,3,'#162039');g.strokeStyle='#4b2a46';g.lineWidth=1.5;g.beginPath();g.arc(0,-3,4,.1,Math.PI-.1);g.stroke();g.restore()}
function rocket(){g.save();g.translate(ship,H-68);if(inv>0&&Math.floor(time*13)%2===0)g.globalAlpha=.5;let flame=g.createLinearGradient(0,24,0,85);flame.addColorStop(0,'white');flame.addColorStop(.27,'#fff68d');flame.addColorStop(.6,'#ff9629');flame.addColorStop(1,'#ff3c1200');g.shadowColor='#ffab27';g.shadowBlur=15;g.fillStyle=flame;g.beginPath();g.moveTo(-10,21);g.quadraticCurveTo(-17,44,0,70+Math.sin(time*45)*11);g.quadraticCurveTo(17,44,10,21);g.fill();g.shadowBlur=0;let red=g.createLinearGradient(-25,0,25,0);red.addColorStop(0,'#ac153b');red.addColorStop(.5,'#ff5b75');red.addColorStop(1,'#9b1538');g.fillStyle=red;g.beginPath();g.moveTo(-14,1);g.lineTo(-27,30);g.lineTo(-9,21);g.lineTo(9,21);g.lineTo(27,30);g.lineTo(14,1);g.fill();let m=g.createLinearGradient(-19,0,19,0);m.addColorStop(0,'#7084a6');m.addColorStop(.33,'white');m.addColorStop(.7,'#d7e7ff');m.addColorStop(1,'#617b9f');g.fillStyle=m;g.beginPath();g.moveTo(0,-42);g.bezierCurveTo(-25,-21,-19,14,-14,23);g.quadraticCurveTo(0,32,14,23);g.bezierCurveTo(19,14,25,-21,0,-42);g.fill();g.fillStyle=red;g.beginPath();g.moveTo(0,-42);g.quadraticCurveTo(-9,-34,-14,-23);g.quadraticCurveTo(0,-28,14,-23);g.quadraticCurveTo(9,-34,0,-42);g.fill();circle(0,-9,12,'#b8244b');let win=g.createRadialGradient(-4,-14,1,0,-9,11);win.addColorStop(0,'white');win.addColorStop(.5,'#48d5ff');win.addColorStop(1,'#1150a0');circle(0,-9,9,win);circle(-4,-13,2,'white');g.restore()}
function explosion(x,y,color,large=false){let n=large?36:15;for(let i=0;i<n;i++){let a=Math.random()*Math.PI*2,s=(large?180:105)*(.3+Math.random());bits.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,r:2+Math.random()*4,life:.45+Math.random()*.35,color:i%5===0?'white':color})}waves.push({x,y,r:5,max:large?118:45,life:large?.55:.32,color});fx(large?'big':'boom')}
function hud(){$('score').textContent='🪙 '+score;$('level').textContent='Nivel '+level;$('hearts').textContent='❤️'.repeat(lives)+'🖤'.repeat(3-lives);for(let i=0;i<3;i++)$('c'+i).textContent=cool[i]>time?(cool[i]-time).toFixed(1)+' s':'Lista'}
function fire(){if(!active||paused||cool[weapon]>time)return;cool[weapon]=time+cd[weapon];shots.push({x:ship,y:H-106,vy:[-230,-900,-340][weapon],type:weapon,life:weapon===2?1.25:2,hits:0,seen:[]});fx(['bullet','laser','grenade'][weapon])}
function hit(e,withBlast=true){if(e.dead)return;e.dead=true;score+=e.coin?10:5;if(e.coin){explosion(e.x,e.y,'#ffd54a');fx('coin')}else if(withBlast)explosion(e.x,e.y,e.color[1])}
function grenade(s){explosion(s.x,s.y,'#ff9b35',true);enemies.forEach(e=>{if(!e.dead&&!e.coin&&Math.hypot(e.x-s.x,e.y-s.y)<125){e.dead=true;score+=5;explosion(e.x,e.y,e.color[1])}})}
function spawnEnemy(){let coin=Math.random()<.2,ci=Math.floor(Math.random()*colors.length);enemies.push({x:34+Math.random()*(W-68),y:-40,coin,color:colors[ci],spriteIndex:ci,phase:Math.random()*6,dead:false})}
function draw(){let bg=g.createLinearGradient(0,0,0,H);bg.addColorStop(0,'#070c28');bg.addColorStop(.65,'#172a65');bg.addColorStop(1,'#3686c4');g.fillStyle=bg;g.fillRect(0,0,W,H);for(let s of stars){g.globalAlpha=.4+s.r/2;circle(s.x,s.y,s.r,'#d4f0ff')}g.globalAlpha=1;let earth=g.createRadialGradient(180,570,5,180,570,240);earth.addColorStop(0,'#60c6eb');earth.addColorStop(.55,'#2877ba');earth.addColorStop(1,'#17416c00');g.fillStyle=earth;g.beginPath();g.ellipse(180,570,285,135,0,Math.PI,Math.PI*2);g.fill();for(let e of enemies){if(e.coin){g.shadowColor='#ffd13d';g.shadowBlur=12;circle(e.x,e.y,15,'#d58c15');circle(e.x,e.y,11,'#ffe16b');g.shadowBlur=0;g.textAlign='center';g.font='bold 16px sans-serif';g.fillStyle='#aa761a';g.fillText('★',e.x,e.y+5)}else plush(e)}for(let s of shots){g.save();if(s.type===0){g.shadowColor='#ffe7a0';g.shadowBlur=10;g.fillStyle='#fff0aa';g.fillRect(s.x-3,s.y-10,6,20)}if(s.type===1){g.shadowColor='#00caff';g.shadowBlur=20;g.strokeStyle='#1abfff';g.lineWidth=12;g.beginPath();g.moveTo(s.x,s.y+30);g.lineTo(s.x,s.y-40);g.stroke();g.strokeStyle='white';g.lineWidth=3;g.stroke()}if(s.type===2){g.shadowColor='#ffab36';g.shadowBlur=12;circle(s.x,s.y,10,'#3b475f');circle(s.x-3,s.y-3,3,'#ffb64e')}g.restore()}for(let p of bits){g.globalAlpha=Math.max(0,p.life/.8);g.shadowColor=p.color;g.shadowBlur=8;circle(p.x,p.y,p.r,p.color)}g.globalAlpha=1;for(let w of waves){g.globalAlpha=Math.max(0,w.life/.55);g.strokeStyle=w.color;g.lineWidth=5;g.beginPath();g.arc(w.x,w.y,w.r,0,Math.PI*2);g.stroke()}g.globalAlpha=1;g.shadowBlur=0;rocket()}
function update(dt){time+=dt;level=1+Math.floor(time/19);inv=Math.max(0,inv-dt);spawn+=dt;if(spawn>Math.max(.34,1.05-level*.06)){spawn=0;spawnEnemy()}if(holding)fire();if(moveDirection)ship=Math.max(27,Math.min(W-27,ship+moveDirection*220*dt));for(let s of stars){s.y+=s.v*dt;if(s.y>H)s.y=0}for(let s of shots){s.y+=s.vy*dt;s.life-=dt;if(s.type===2&&s.y<135){grenade(s);s.life=0;continue}if(s.type!==2){for(let e of enemies){if(e.dead||e.coin||s.seen.includes(e))continue;if(Math.abs(e.x-s.x)<22&&Math.abs(e.y-s.y)<30){hit(e);s.seen.push(e);s.hits++;if(s.type===0||s.hits>=2){s.life=0;break}}}}}shots=shots.filter(s=>s.life>0&&s.y>-70);for(let e of enemies){if(e.dead)continue;e.y+=(108+level*27)*dt;if(inv<=0&&Math.abs(e.x-ship)<27&&e.y>H-110&&e.y<H-35){if(e.coin)hit(e);else{e.dead=true;lives--;inv=1;explosion(e.x,e.y,e.color[1]);fx('hurt');if(!lives){end();return}}}}enemies=enemies.filter(e=>!e.dead&&e.y<H+50);for(let p of bits){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=70*dt;p.life-=dt}bits=bits.filter(p=>p.life>0);for(let w of waves){w.life-=dt;w.r+=(w.max-w.r)*Math.min(1,dt*9)}waves=waves.filter(w=>w.life>0);hud()}
function frame(t){if(!active||paused)return;if(!last)last=t;let dt=Math.min(.04,(t-last)/1000);last=t;update(dt);draw();if(active)raf=requestAnimationFrame(frame)}
function start(){cancelAnimationFrame(raf);ship=180;enemies=[];shots=[];bits=[];waves=[];score=0;lives=3;level=1;time=0;spawn=0;inv=0;cool=[0,0,0];active=true;paused=false;holding=false;moveDirection=0;dragPointer=null;last=0;$('cover').style.display='none';$('pause').disabled=false;$('pause').textContent='Pausar';audioInit();musicStart();hud();raf=requestAnimationFrame(frame)}
function end(){active=false;holding=false;musicStop();$('pause').disabled=true;$('cover').style.display='flex';$('cover').innerHTML='<div class="rocket-icon">🏆</div><h1>¡Fin de la partida!</h1><p id="result"></p><button id="again">Volver a jugar</button>';$('result').textContent='Puntuación: '+score;$('again').addEventListener('click',start)}
function select(i){weapon=i;for(let j=0;j<3;j++)$('w'+j).setAttribute('aria-pressed',String(i===j))}
function buttons(){$('music').textContent=musicOn?'🎵 Música ON':'🎵 Música OFF';$('sfx').textContent=sfxOn?'🔊 Efectos ON':'🔇 Efectos OFF'}
// Un dedo puede arrastrar el cohete mientras otro mantiene pulsado DISPARAR.
function moveShip(e){const r=cv.getBoundingClientRect();ship=Math.max(27,Math.min(W-27,(e.clientX-r.left)/r.width*W))}
cv.addEventListener('pointerdown',e=>{if(!active||paused||dragPointer!==null)return;dragPointer=e.pointerId;cv.setPointerCapture(e.pointerId);moveShip(e)});
cv.addEventListener('pointermove',e=>{if(active&&!paused&&dragPointer===e.pointerId)moveShip(e)});
for(const ev of ['pointerup','pointercancel','lostpointercapture'])cv.addEventListener(ev,e=>{if(e.pointerId===dragPointer)dragPointer=null});
function directionalButton(id,dir){const el=$(id);el.addEventListener('pointerdown',e=>{if(!active||paused)return;e.preventDefault();moveDirection=dir;el.setPointerCapture(e.pointerId);ship=Math.max(27,Math.min(W-27,ship+dir*12))});for(const ev of ['pointerup','pointercancel','lostpointercapture'])el.addEventListener(ev,()=>{if(moveDirection===dir)moveDirection=0});el.addEventListener('click',()=>{if(active&&!paused)ship=Math.max(27,Math.min(W-27,ship+dir*18))})}
directionalButton('left',-1);directionalButton('right',1);
for(let i=0;i<3;i++)$('w'+i).addEventListener('click',()=>select(i));
$('fire').addEventListener('pointerdown',e=>{if(!active||paused)return;e.preventDefault();holding=true;fire();$('fire').setPointerCapture(e.pointerId)});
['pointerup','pointercancel','lostpointercapture'].forEach(ev=>$('fire').addEventListener(ev,()=>holding=false));$('fire').addEventListener('click',()=>{if(active&&!paused)fire()});
$('pause').addEventListener('click',()=>{if(!active)return;paused=!paused;holding=false;$('pause').textContent=paused?'Continuar':'Pausar';if(paused)musicStop();else{last=0;musicStart();raf=requestAnimationFrame(frame)}});
$('music').addEventListener('click',()=>{musicOn=!musicOn;buttons();if(!musicOn)musicStop();else if(active&&!paused){audioInit();musicStart()}});$('sfx').addEventListener('click',()=>{sfxOn=!sfxOn;buttons();if(sfxOn)audioInit()});$('start').addEventListener('click',start);
window.addEventListener('blur',()=>{if(active&&!paused){paused=true;holding=false;moveDirection=0;dragPointer=null;musicStop();$('pause').textContent='Continuar'}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&active&&!paused){paused=true;holding=false;moveDirection=0;dragPointer=null;musicStop();$('pause').textContent='Continuar'}});
select(0);draw();hud();
